### ISSUE TITLE
Скрипт зависает через 30-60 минут

### ISSUE THREAD

**Issue by IftimeDaniel** [RankoR/SocialCreditBot#1]
Здравствуйте, скрипт, похоже, работает нормально в течение первых 30-60 минут внутри JVM. Но потом как бы зависает, есть идеи, почему это происходит?

**Comment by RankoR** [comment]
@IftimeDaniel приветствую, тоже столкнулся с этой проблемой, но пока не дошли руки подебажить.

**Comment by IftimeDaniel** [comment]
Спасибо за ответ, знаете ли вы, что могло его вызвать?

**Comment by RankoR** [comment]
@IftimeDaniel я наблюдал за контейнером снаружи, по памяти и CPU всё ок, он висит в IDLE, в принципе, вполне вероятно, что есть какая-то проблема с библиотекой для работы с API телеграма, возможно, именно она не присылает новые события. После перезапуска боту прилетают прошлые (те, которые он проигнорировал пока был "повисшим") события, т.е. сервер телеграма считает их не полученными.

Кстати, вы запускали в докере, или без него? Если без него, то с какой версией JRE?

**Comment by IftimeDaniel** [comment]
Мне удалось исправить это, обновив библиотеки внутри "build.gradle.kts"

dependencies {
    implementation("io.github.kotlin-telegram-bot.kotlin-telegram-bot:telegram:6.0.6")
   implementation("org.jetbrains.exposed:exposed-core:0.36.2")
    implementation("org.jetbrains.exposed:exposed-dao:0.36.2")
    implementation("org.jetbrains.exposed:exposed-jdbc:0.36.2")
    implementation("org.xerial:sqlite-jdbc:3.36.0.3")
}

Видимо ошибка была вызвана версией 6.0.4 Kotlin-telegram-bot, 6.0.5 исправил.


Бот работает без проблем более 14 часов.

**Comment by RankoR** [comment]
@IftimeDaniel отпишитесь, пожалуйста, если сломается опять. У меня в последнее время вроде без фиксов до суток доходило, но потом опять висло.
Также буду благодарен пуллреквесту :)
